---
title: Confraria do Kart
timezone: America/Sao_Paulo
collections:
  campeonatos:
    title: Campeonatos
    output: false
  pistas:
    title: Pistas
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: ''
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: blog/:title/
    image: ''
    campeonato: ''
- scope:
    path: ''
    type: campeonatos
  values:
    ano: ''
    etapas:
    - date: ''
      pista: ''
lang: pt_BR
description: ''
baseurl: ''
url: http://confrariadokart.esp.br/
markdown: kramdown
permalink: pretty/
paginate: 10
paginate_path: "/blog/:num/"
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- ".vscode/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- README.md
- package.json
- CNAME
